openapi: 3.0.2
info:
  version: 1.0.0
  title: doer-backend
  description: API for todoist clone.
tags:
  - name: Specification
    description: The swagger API specification
paths:
  /login:
    post:
      tags:
        - Login
      description: login into the todo API
      security:
        - BasicAuth:
            []
      responses:
        "200":
          description: user successfully logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
  /signup:
    post:
      tags:
        - SignIn
      description: sign user into todo app
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        description: The user signing up
      responses:
        "200":
          description: user signed up
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
  /task:
    post:
      tags:
        - Task
      description: save task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        description: The task to be saved
      responses:
        "200":
          description: Sucessfully posted task.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Task body was empty.
        "500":
          description: Error occured while posting data.
  "/task/{id}":
    parameters:
      - in: path
        name: id
        description: id of task.
        required: true
        schema:
          type: string
    delete:
      tags:
        - Task
      description: Deletes task from data store.
      responses:
        "204":
          description: Task deleted.
    put:
      tags:
        - Task
      description: Update data store task.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        description: The task to be saved
        required: true
      responses:
        "204":
          description: Task updated.
  "/{email}/tasks":
    parameters:
      - in: path
        name: email
        description: Email of user whose tasks are to be retrieved.
        required: true
        schema:
          type: string
    get:
      tags:
        - Tasks
      responses:
        "200":
          description: OK
  /spec:
    get:
      tags:
        - Specification
      responses:
        "200":
          description: Return the API specification
servers:
  - url: http://localhost:3000/api/v1
    description: Local development spec
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OpenId:
      type: openIdConnect
      openIdConnectUrl: https://dev-769052.okta.com
  schemas:
    User:
      type: object
      title: user
      required:
        - firstName
        - lastName
        - handle
        - email
        - password
      properties:
        firstName:
          type: string
          example: Johnny
        lastName:
          type: string
          example: Test
        handle:
          type: string
          example: TopJohann28
        email:
          type: string
          example: someuser@example.com
        password:
          type: string
          example: testPassword (don't actually use this please)
    Login:
      type: object
      title: login
      required:
        - firstName
        - lastName
        - handle
        - email
        - token
      properties:
        firstName:
          type: string
          example: Johnny
        lastName:
          type: string
          example: Test
        handle:
          type: string
          example: TopJohann28
        email:
          type: string
          example: someuser@example.com
        token:
          type: string
          example: JWT token
          description: JWT token
    Task:
      type: object
      title: task
      required:
        - email
        - text
      properties:
        project:
          type: string
          example: Chores
        email:
          type: string
          example: sample.user@something.com
        text:
          type: string
          example: Do dishes.
