openapi: 3.0.2
info:
  version: 1.0.0
  title: react-todo-backend
  description: API for backend todoist clone.
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /login:
    post:
      tags:
        - Login
      description: login into the todo API
      responses:
        "200":
          description: user successfully logged in
  /signup:
    post:
      tags:
        - SignIn
      description: sign user into todo app
      consume:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - handle
                - email
                - password
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                handle:
                  type: string
                email:
                  type: string
                password:
                  type: string
        description: The user signing up
      responses:
        "201":
          description: user created
  /task:
    post:
      tags:
        - Task
      description: save task
      consume:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - text
              properties:
                project:
                  type: string
                id:
                  type: string
                text:
                  type: string
                email:
                  type: string
                created:
                  type: string
        description: The task to be saved
      responses:
        "201":
          description: user created
  /spec:
    get:
      tags:
        - Specification
      responses:
        "200":
          description: Return the API specification
servers:
  - url: /api/v1
components:
  schemas:
    User:
      type: object
      title: user
      required:
        - firstName
        - lastName
        - handle
        - email
        - password
      properties:
        firstName:
          type: string
          example: Johnny
        lastName:
          type: string
          example: Test
        handle:
          type: string
          example: TopJohann28
        email:
          type: string
          example: someuser@example.com
        password:
          type: string
          example: testPassword (don't actually use this please)
    Task:
      type: object
      title: task
      required:
        - id
        - text
        - email
      properties:
        project:
          type: string
          example: Chore
        id:
          type: string
          example: 00112233-4455-6677-8899-aabbccddeeff
        email:
          type: string
          example: someuser@example.com
        text:
          type: string
          example: Wash the dishes
        createdTime:
          type: string
          example: 12/06/1992T01:01:01